# Cache node modules - speeds up future builds
cache:
  paths:
    - node_modules

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  image: armdocker.rnd.ericsson.se/proj-ldc/common_base_os_release/sles:4.0.0-41
  before_script:
    - zypper addrepo --gpgcheck-strict -f "https://arm.sero.gic.ericsson.se/artifactory/proj-ldc-repo-rpm-local/common_base_os/sles/4.0.0-41" CBO_REPO && zypper --gpg-auto-import-keys refresh -f && zypper install -l -y nodejs16 npm && zypper clean --all
  script:
    - npm --version
    - npm cache clean --force
    # - npm config list
    - npm config set registry https://arm.seli.gic.ericsson.se/artifactory/api/npm/npm-remote/
    - npm install
    - npm install @eds/vanilla@3.15.0 --force --registry https://arm.rnd.ki.sw.ericsson.se/artifactory/api/npm/proj-eds-npm-local
    - CI=false npm run build
    # - npm run test:ci
  cache:
    paths:
      - build/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - ./build
  only:
    - tags
  except:
    - ^(?!main).+@

test:
  extends: build
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm --version
    - npm cache clean --force
    - npm config set registry https://arm.seli.gic.ericsson.se/artifactory/api/npm/npm-remote/
    - npm install
    - npm install @eds/vanilla@3.15.0 --force --registry https://arm.rnd.ki.sw.ericsson.se/artifactory/api/npm/proj-eds-npm-local
    - npm run test:ci
  only:
    - tags
  except:
    - ^(?!main).+@

release:
  stage: release
  needs: [ "build" ]
  image:
    name: armdocker.rnd.ericsson.se/proj-dsi-portal/external/kaniko-project:debug
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$ARTIFACTORY_DOCKER_URL\":{\"username\":\"$ARTIFACTORY_DOCKER_USER\",\"password\":\"$ARTIFACTORY_DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
    - tag="0.0.1"
  script:
    - /kaniko/executor --insecure --skip-tls-verify --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination armdocker.rnd.ericsson.se/proj-pdp/pdp-web:$CI_COMMIT_TAG
  only:
    - tags
  except:
    - ^(?!main).+@

deploy:
  stage: deploy
  image:
    name: armdocker.rnd.ericsson.se/proj-dsi-portal/util/des-cbo:1.0.0
    entrypoint: [ "" ]
  before_script:
    - mkdir -p /home/jovyan/.kube
    - echo ${KUBE_CONFIG_TARGET} > ${KUBECONFIG}
    # - kubectl create namespace pdp || echo "Namespace exists!"
    # - kubectl annotate namespace pdp field.cattle.io/projectId=$RANCHERID --overwrite=true
  script:
    - helm upgrade -f $CI_PROJECT_DIR/helm/values.yaml --set image.tag=$CI_COMMIT_TAG pdp-web-dev helm --namespace=pdp
    - sleep 30
    - kubectl get pods --namespace=pdp
  only:
    - tags
  except:
    - ^(?!main).+@
